baseURL = "https://naclist.github.io/naclist-portfolio/"
canonifyURLs = true    
languageCode = "en-us"
title = "Naclist"
theme = "nacstyle"

[menu]

[[menu.main]]
  name = "Home"
  url = "https://naclist.github.io/naclist-portfolio/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "naclist-portfolio/publications/"
  weight = 2

[[menu.main]]
  name = "Skills"
  url = "naclist-portfolio/skills/"
  weight = 3

[[menu.main]]
  name = "Ambitions"
  url = "naclist-portfolio/ambitions/"
  weight = 4

[[menu.main]]
  name = "Blogs"
  url = "naclist-portfolio/blogs/"
  weight = 5

[[menu.main]]
  name = "Arts"
  url = "naclist-portfolio/arts/"
  weight = 6

[[menu.main]]
  name = "Kindred Spirits"
  url = "naclist-portfolio/friends/"
  weight = 7

[[menu.main]]
  name = "About"
  url = "naclist-portfolio/about/"
  weight = 8

